In [1]:
import numpy as np

In [2]:
myZero = np.zeros([3, 5])  #全0 矩阵

In [3]:
print(myZero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
myOnes = np.ones([3, 5]) #全1矩阵

In [5]:
print(myOnes)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
myRand = np.random.rand(3,4)  # 3行4列的 0～1间的随机数

In [7]:
print(myRand)

[[0.3866547  0.98743144 0.71804844 0.099076  ]
 [0.91588758 0.27060332 0.52537537 0.01649248]
 [0.34784277 0.56811528 0.9669045  0.51947737]]


In [8]:
myEye = np.eye(3)   #3*3的单位矩阵

In [9]:
print(myEye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
from numpy import *   #导入numpy下的所有函数

In [11]:
myOnes = ones([3,3])
myEye = eye(3)
print(myOnes + myEye)
print(myOnes - myEye)

[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]
[[0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]


In [12]:
myArray = array([[1,2,3], [4,5,6], [7,8,9]])
a = 10
print(a * myArray)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [13]:
myMatrix = mat([[1,2,3], [4,5,6], [7,8,9]])
a = 10
print( a * myMatrix)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [15]:

myMatrix

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
myArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
print(sum(myMatrix))
print(sum(myArray))

45
45


In [18]:
myMatrix2 = 1.5 * ones([3,3])
print(multiply(myMatrix,myMatrix2))   #对应元素相乘

[[ 1.5  3.   4.5]
 [ 6.   7.5  9. ]
 [10.5 12.  13.5]]


In [19]:
print(power(myMatrix,2))

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [20]:
myMatrix3 = mat([[1], [2], [3]])
print(myMatrix * myMatrix3)   #矩阵相乘

[[14]
 [32]
 [50]]


In [24]:
print("--------原矩阵-------")
print(myMatrix)   #原矩阵
print("--------显示转置矩阵-------")
print(myMatrix.T) #显示转置后的矩阵，原矩阵不便
print("--------原矩阵-------")
print(myMatrix)
myMatrix.transpose() # 转置矩阵  ##好像不起作用
print("--------转置后-------")
print(myMatrix)
myMatrix.transpose() # 再次转置回来
print("--------原矩阵-------")
print(myMatrix)

--------原矩阵-------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------显示转置矩阵-------
[[1 4 7]
 [2 5 8]
 [3 6 9]]
--------原矩阵-------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------转置后-------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------原矩阵-------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
A = mat([[1,2,4,5,7], [9,12,11,8,2], [6,4,3,2,1],[9,1,3,4,5],[0,2,3,4,1]])
invA = np.linalg.inv(A)
print("inv(A):", invA)
print("-------------A*invA 得单位矩阵--------")
print(A * invA)

inv(A): [[-7.14285714e-02 -1.23152709e-02  5.29556650e-02  9.60591133e-02
  -8.62068966e-03]
 [ 2.14285714e-01 -3.76847291e-01  1.22044335e+00 -4.60591133e-01
   3.36206897e-01]
 [-2.14285714e-01  8.25123153e-01 -2.04802956e+00  5.64039409e-01
  -9.22413793e-01]
 [ 5.11521867e-17 -4.13793103e-01  8.79310345e-01 -1.72413793e-01
   8.10344828e-01]
 [ 2.14285714e-01 -6.65024631e-02  1.85960591e-01 -8.12807882e-02
  -1.46551724e-01]]
-------------A*invA 得单位矩阵--------
[[ 1.00000000e+00 -6.93889390e-17  1.30451205e-15 -8.32667268e-17
   1.94289029e-16]
 [ 1.66533454e-16  1.00000000e+00  9.43689571e-16  3.88578059e-16
   5.55111512e-17]
 [ 0.00000000e+00  6.93889390e-17  1.00000000e+00  3.60822483e-16
  -1.94289029e-16]
 [-1.11022302e-16  1.24900090e-16 -3.05311332e-16  1.00000000e+00
  -3.05311332e-16]
 [ 2.77555756e-17 -1.52655666e-16  9.15933995e-16 -2.77555756e-17
   1.00000000e+00]]


In [31]:
#计算L2范数
A = [8, 1, 6]
#手工计算
modA = sqrt(sum(power(A,2)))
print("modA:",modA)

#使用库函数计算
normA = linalg.norm(A)
print("normA:", normA)

modA: 10.04987562112089
normA: 10.04987562112089


In [33]:
#向量的欧式距离计算
vector1  = mat([1,2,3])
vector2 = mat([4,5,6])
print(sqrt((vector1 - vector2) * (vector1-vector2).T))

[[5.19615242]]


In [34]:
#向量的曼哈顿距离计算
print(sum(abs(vector1 - vector2)))

9
